### ISSUE TITLE
TraCI version

### ISSUE THREAD

**Issue by Kunal-Kumar-Sahoo** [maxbren/Multi-agent-Distrubted-PPO-Traffc-light-control#5]
Can you specify what version of `TraCI` library did you use because while implementing `main.py` code, I am encountering the following error:

```
Traceback (most recent call last):
  File "/home/kunalkumarsahoo/mambaforge/envs/cistup/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/home/kunalkumarsahoo/mambaforge/envs/cistup/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/kunalkumarsahoo/Playground/CiSTUP/research_internship/Multi-Agent-Distributed-PPO-Traffc-light-control/run_agent_parallel.py", line 17, in train_worker
    worker = PPOWorker(constants, device, env, None, shared_NN, local_NN, optimizer, id)
  File "/home/kunalkumarsahoo/Playground/CiSTUP/research_internship/Multi-Agent-Distributed-PPO-Traffc-light-control/workers/ppo_worker.py", line 16, in __init__
    self.state = self.env.reset()
  File "/home/kunalkumarsahoo/Playground/CiSTUP/research_internship/Multi-Agent-Distributed-PPO-Traffc-light-control/environments/environment.py", line 77, in reset
    if self.conn_label in traci.main._connections:
AttributeError: module 'traci' has no attribute 'main'
```

**Comment by quinter770** [comment]
Hello, could you tell me which version you chose in the end? Looking forward to your reply!
